[package]
name = "layerfs-directory-proof"
version = "0.0.0"
edition = "2021"

[workspace]

[dependencies]
layerfs-sdk = { path = "../../../../../../crates/layerfs-sdk" }
layerfs-content = { path = "../../../../../../crates/layerfs-content" }
layerfs-layerstack-store = { path = "../../../../../../crates/layerfs-layerstack-store" }
libc = "0.2"
